### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by a87Nozaki** [a87Nozaki/furima-31578#10]
フリマアプリのURL https://furima-31578.herokuapp.com
Basic認証のID admin
パスワード 2222
出品者用のメールアドレス nozaki@test.com
出品者用のパスワード nozaki123
購入者用のメールアドレス kitada@test.com
購入者用のパスワード kitada123
購入用カードの番号 4242424242424242
                          期限 3月 23年
セキュリティコード 123

**Comment by naru6117** [comment]
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/49669977/100837070-d444c880-34b3-11eb-87f6-173004596f76.png)

ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
